### ISSUE TITLE
mall-admin-ui 运行 npm run dev 出错

### ISSUE THREAD

**Issue by liufengvling** [johntostring/millimall#4]
PS E:\workspace_git\millimall\mall-admin-ui> cnpm run dev

> mall-admin-ui@1.0.0 dev E:\workspace_git\millimall\mall-admin-ui
> node build/dev-server.js

module.js:471
    throw err;
    ^

Error: Cannot find module 'E:\workspace_git\millimall\mall-admin-ui\build\dev-server.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "C:\\Users\\hades\\AppData\\Roaming\\npm\\node_modules\\cnpm\\node_m
odules\\npm\\bin\\npm-cli.js" "--userconfig=C:\\Users\\hades\\.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "
--registry=https://registry.npm.taobao.org" "run" "dev"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mall-admin-ui@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mall-admin-ui@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mall-admin-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mall-admin-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mall-admin-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\workspace_git\millimall\mall-admin-ui\npm-debug.log

**Comment by johntostring** [comment]
Have you ever tried `npm run dev`?

**Comment by liufengvling** [comment]
yes，i tried。 is some files in ***build folder*** not upload  ？ or how to generate them？
